FROM python:3.7

RUN apt-get update && apt -y install gfortran libopenmpi-dev make git

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN cd /home && git clone https://github.com/ydluo/qdyn && cd qdyn/src && make clean && make

EXPOSE 9000

CMD jupyter notebook --no-browser --port=9000 --ip='*' --allow-root --notebook-dir=/home
