FROM python:3.7-slim

RUN apt-get update && apt -y install gfortran libopenmpi-dev make git ffmpeg libgeos-dev libproj-dev proj-data proj-bin

COPY docker/requirements.txt pyacs/pyacs-0.65.5.tar.gz pyacs/pyeq-0.54.3.tar.gz .
RUN pip install --no-cache-dir --use-feature=2020-resolver -r requirements.txt
RUN pip install --no-cache-dir --use-feature=2020-resolver pyacs-0.65.5.tar.gz pyeq-0.54.3.tar.gz

RUN cd /home && git clone https://github.com/ydluo/qdyn && cd qdyn/src && make clean && make
RUN cd /home && git clone https://github.com/martijnende/jDAS

EXPOSE 9000

CMD jupyter notebook --no-browser --port=9000 --ip='*' --allow-root --notebook-dir=/home
